# Generated by Django 4.2.4 on 2023-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='randrdetails',
            name='discription',
            field=models.CharField(default='Use the html tags to make the content look well', editable=False, max_length=220),
        ),
    ]
