# Generated by Django 4.2.4 on 2023-09-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0002_randrdetails_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randrdetails',
            old_name='discription',
            new_name='description',
        ),
    ]
