# Generated by Django 4.2.4 on 2023-09-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0003_rename_discription_randrdetails_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randrdetails',
            name='description',
        ),
    ]
