# Generated by Django 4.2.4 on 2023-09-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0004_remove_randrdetails_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('phnum', models.CharField(max_length=16)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
