# Generated by Django 4.2.4 on 2023-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0008_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(),
        ),
    ]
