# Generated by Django 4.2.4 on 2023-09-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0009_alter_contact_date_alter_contact_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
    ]
