# Generated by Django 5.0.1 on 2024-04-26 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0012_country_alter_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(default=datetime.time(12, 1, 39, 594771)),
        ),
    ]
